export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    CREATE_ACCOUNT_REQUEST: 'CREATE_ACCOUNT_REQUEST',
    CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',

    LOGIN_WITH_GOOGLE_REQUEST: 'LOGIN_WITH_GOOGLE_REQUEST',
    LOGIN_WITH_GOOGLE_SUCCESS: 'LOGIN_WITH_GOOGLE_SUCCESS',
    LOGIN_WITH_GOOGLE_FAILURE: 'LOGIN_WITH_GOOGLE_FAILURE',
}